// src/lib/mockData.js
// Development-only mock data. Replace imports with real Supabase hooks module by module.
// Never import this file in production code paths.

export const MOCK_ADMINS = [
  {
    id: 'adm-001',
    name: 'Adaeze Okafor',
    email: 'adaeze@chauffeur.app',
    role: 'super_admin',
    status: 'active',
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'adm-002',
    name: 'Chukwuemeka Eze',
    email: 'emeka@chauffeur.app',
    role: 'ops_admin',
    status: 'active',
    created_at: '2024-02-01T10:30:00Z',
  },
  {
    id: 'adm-003',
    name: 'Fatimah Al-Hassan',
    email: 'fatimah@chauffeur.app',
    role: 'finance_admin',
    status: 'active',
    created_at: '2024-02-14T08:00:00Z',
  },
  {
    id: 'adm-004',
    name: 'Tunde Adeyemi',
    email: 'tunde@chauffeur.app',
    role: 'support_agent',
    status: 'active',
    created_at: '2024-03-05T11:15:00Z',
  },
  {
    id: 'adm-005',
    name: 'Ngozi Nwosu',
    email: 'ngozi@chauffeur.app',
    role: 'inspection_officer',
    status: 'active',
    created_at: '2024-03-20T09:45:00Z',
  },
  {
    id: 'adm-006',
    name: 'Bello Musa',
    email: 'bello@chauffeur.app',
    role: 'ops_admin',
    status: 'suspended',
    created_at: '2024-04-10T14:00:00Z',
  },
];

export const MOCK_DRIVERS = [
  {
    id: 'drv-001',
    full_name: 'Emeka Obi',
    email: 'emeka.obi@gmail.com',
    phone: '+234 801 234 5678',
    date_of_birth: '1990-05-12',
    residential_address: '14 Adeola Odeku Street, Victoria Island, Lagos',
    government_id_number: 'NIN-12345678901',
    selfie_url: 'https://i.pravatar.cc/150?img=11',
    face_match_score: 94.7,
    face_match_status: 'pass',
    status: 'active',
    verification_status: 'approved',
    rating: 4.9,
    commission_rate: null,
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'drv-002',
    full_name: 'Abiodun Salami',
    email: 'abiodun.s@yahoo.com',
    phone: '+234 802 345 6789',
    date_of_birth: '1987-11-23',
    residential_address: '7 Bourdillon Road, Ikoyi, Lagos',
    government_id_number: 'NIN-98765432109',
    selfie_url: 'https://i.pravatar.cc/150?img=12',
    face_match_score: 88.3,
    face_match_status: 'pass',
    status: 'active',
    verification_status: 'approved',
    rating: 4.7,
    commission_rate: 12.0,
    created_at: '2024-03-15T10:30:00Z',
  },
  {
    id: 'drv-003',
    full_name: 'Ifeanyi Okeke',
    email: 'ifeanyi.okeke@gmail.com',
    phone: '+234 803 456 7890',
    date_of_birth: '1993-02-08',
    residential_address: '22 Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
    government_id_number: 'NIN-11223344556',
    selfie_url: 'https://i.pravatar.cc/150?img=13',
    face_match_score: 61.2,
    face_match_status: 'needs_review',
    status: 'under_review',
    verification_status: 'pending',
    rating: 0,
    commission_rate: null,
    created_at: '2024-05-10T14:00:00Z',
  },
  {
    id: 'drv-004',
    full_name: 'Kehinde Lawal',
    email: 'kehinde.l@hotmail.com',
    phone: '+234 804 567 8901',
    date_of_birth: '1985-07-30',
    residential_address: '5 Glover Road, Ikoyi, Lagos',
    government_id_number: 'NIN-55667788990',
    selfie_url: 'https://i.pravatar.cc/150?img=14',
    face_match_score: 97.1,
    face_match_status: 'pass',
    status: 'suspended',
    verification_status: 'approved',
    rating: 4.2,
    commission_rate: null,
    created_at: '2024-02-20T09:15:00Z',
  },
  {
    id: 'drv-005',
    full_name: 'Chidi Nnamdi',
    email: 'chidi.n@gmail.com',
    phone: '+234 805 678 9012',
    date_of_birth: '1991-09-14',
    residential_address: '31 Eko Atlantic, Lagos',
    government_id_number: 'NIN-66778899001',
    selfie_url: 'https://i.pravatar.cc/150?img=15',
    face_match_score: 92.5,
    face_match_status: 'pass',
    status: 'inactive',
    verification_status: 'approved',
    rating: 4.6,
    commission_rate: null,
    created_at: '2024-04-05T07:30:00Z',
  },
  {
    id: 'drv-006',
    full_name: 'Segun Adebayo',
    email: 'segun.adebayo@gmail.com',
    phone: '+234 806 789 0123',
    date_of_birth: '1988-12-01',
    residential_address: '9 Lekki Phase 1, Lagos',
    government_id_number: 'NIN-77889900112',
    selfie_url: 'https://i.pravatar.cc/150?img=16',
    face_match_score: 85.0,
    face_match_status: 'pass',
    status: 'active',
    verification_status: 'approved',
    rating: 4.8,
    commission_rate: 10.0,
    created_at: '2024-01-28T11:00:00Z',
  },
];

export const MOCK_DRIVER_APPLICATIONS = [
  {
    id: 'app-001',
    driver_id: 'drv-003',
    driver: { full_name: 'Ifeanyi Okeke', email: 'ifeanyi.okeke@gmail.com', phone: '+234 803 456 7890' },
    state: 'under_review',
    rejection_reason: null,
    reviewed_by: 'adm-002',
    submitted_at: '2024-05-10T14:00:00Z',
    updated_at: '2024-05-11T09:30:00Z',
  },
  {
    id: 'app-002',
    driver_id: 'drv-007',
    driver: { full_name: 'Rotimi Fasanya', email: 'rotimi.f@gmail.com', phone: '+234 807 890 1234' },
    state: 'new',
    rejection_reason: null,
    reviewed_by: null,
    submitted_at: '2024-05-12T08:15:00Z',
    updated_at: '2024-05-12T08:15:00Z',
  },
  {
    id: 'app-003',
    driver_id: 'drv-008',
    driver: { full_name: 'Amina Suleiman', email: 'amina.s@yahoo.com', phone: '+234 808 901 2345' },
    state: 'inspection_scheduled',
    rejection_reason: null,
    reviewed_by: 'adm-002',
    submitted_at: '2024-05-08T10:00:00Z',
    updated_at: '2024-05-09T14:20:00Z',
  },
  {
    id: 'app-004',
    driver_id: 'drv-001',
    driver: { full_name: 'Emeka Obi', email: 'emeka.obi@gmail.com', phone: '+234 801 234 5678' },
    state: 'approved',
    rejection_reason: null,
    reviewed_by: 'adm-001',
    submitted_at: '2024-03-01T08:00:00Z',
    updated_at: '2024-03-05T16:00:00Z',
  },
  {
    id: 'app-005',
    driver_id: 'drv-009',
    driver: { full_name: 'Olu Martins', email: 'olu.m@gmail.com', phone: '+234 809 012 3456' },
    state: 'rejected',
    rejection_reason: 'Vehicle not compliant with platform standards',
    reviewed_by: 'adm-002',
    submitted_at: '2024-05-06T13:00:00Z',
    updated_at: '2024-05-07T10:45:00Z',
  },
  {
    id: 'app-006',
    driver_id: 'drv-010',
    driver: { full_name: 'Blessing Okonkwo', email: 'blessing.o@gmail.com', phone: '+234 810 123 4567' },
    state: 'correction_requested',
    rejection_reason: null,
    reviewed_by: 'adm-002',
    submitted_at: '2024-05-11T11:30:00Z',
    updated_at: '2024-05-11T15:00:00Z',
  },
];

export const MOCK_VEHICLES = [
  {
    id: 'veh-001',
    driver_id: 'drv-001',
    driver: { full_name: 'Emeka Obi' },
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    plate_number: 'LND 421 GH',
    colour: 'Midnight Black',
    insurance_doc_url: '/mock/docs/insurance_001.pdf',
    registration_doc_url: '/mock/docs/reg_001.pdf',
    compliance_status: 'approved',
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'veh-002',
    driver_id: 'drv-002',
    driver: { full_name: 'Abiodun Salami' },
    make: 'Honda',
    model: 'Accord',
    year: 2021,
    plate_number: 'LND 887 KJ',
    colour: 'Pearl White',
    insurance_doc_url: '/mock/docs/insurance_002.pdf',
    registration_doc_url: '/mock/docs/reg_002.pdf',
    compliance_status: 'approved',
    created_at: '2024-03-15T10:30:00Z',
  },
  {
    id: 'veh-003',
    driver_id: 'drv-004',
    driver: { full_name: 'Kehinde Lawal' },
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2020,
    plate_number: 'LND 334 AB',
    colour: 'Graphite Grey',
    insurance_doc_url: '/mock/docs/insurance_003.pdf',
    registration_doc_url: '/mock/docs/reg_003.pdf',
    compliance_status: 'inspection_due',
    created_at: '2024-02-20T09:15:00Z',
  },
  {
    id: 'veh-004',
    driver_id: 'drv-005',
    driver: { full_name: 'Chidi Nnamdi' },
    make: 'Lexus',
    model: 'ES 350',
    year: 2023,
    plate_number: 'LND 119 ZZ',
    colour: 'Obsidian Blue',
    insurance_doc_url: '/mock/docs/insurance_004.pdf',
    registration_doc_url: '/mock/docs/reg_004.pdf',
    compliance_status: 'approved',
    created_at: '2024-04-05T07:30:00Z',
  },
  {
    id: 'veh-005',
    driver_id: 'drv-006',
    driver: { full_name: 'Segun Adebayo' },
    make: 'BMW',
    model: '5 Series',
    year: 2022,
    plate_number: 'LND 560 MN',
    colour: 'Alpine White',
    insurance_doc_url: '/mock/docs/insurance_005.pdf',
    registration_doc_url: '/mock/docs/reg_005.pdf',
    compliance_status: 'expired',
    created_at: '2024-01-28T11:00:00Z',
  },
];

export const MOCK_RIDERS = [
  {
    id: 'rdr-001',
    full_name: 'Chioma Ibe',
    email: 'chioma.ibe@gmail.com',
    phone: '+234 811 234 5678',
    status: 'active',
    wallet_balance: 45000.00,
    rating: 4.8,
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: 'rdr-002',
    full_name: 'Oluwaseun Bakare',
    email: 'seun.bakare@yahoo.com',
    phone: '+234 812 345 6789',
    status: 'active',
    wallet_balance: 12500.00,
    rating: 4.5,
    created_at: '2024-03-22T14:30:00Z',
  },
  {
    id: 'rdr-003',
    full_name: 'Maryam Aliyu',
    email: 'maryam.a@gmail.com',
    phone: '+234 813 456 7890',
    status: 'suspended',
    wallet_balance: 3200.00,
    rating: 3.1,
    created_at: '2024-01-05T08:45:00Z',
  },
  {
    id: 'rdr-004',
    full_name: 'Adekunle Fashola',
    email: 'adekunle.f@hotmail.com',
    phone: '+234 814 567 8901',
    status: 'active',
    wallet_balance: 87000.00,
    rating: 4.9,
    created_at: '2024-04-18T09:00:00Z',
  },
  {
    id: 'rdr-005',
    full_name: 'Zainab Umar',
    email: 'zainab.umar@gmail.com',
    phone: '+234 815 678 9012',
    status: 'under_review',
    wallet_balance: 500.00,
    rating: 2.8,
    created_at: '2024-05-01T16:20:00Z',
  },
  {
    id: 'rdr-006',
    full_name: 'Taiwo Afolabi',
    email: 'taiwo.a@gmail.com',
    phone: '+234 816 789 0123',
    status: 'active',
    wallet_balance: 24750.00,
    rating: 4.6,
    created_at: '2024-03-11T11:10:00Z',
  },
];

export const MOCK_RIDES = [
  {
    id: 'rid-001',
    rider_id: 'rdr-001',
    driver_id: 'drv-001',
    rider: { full_name: 'Chioma Ibe' },
    driver: { full_name: 'Emeka Obi' },
    trip_status: 'in_progress',
    service_tier: 'executive',
    pickup_address: '1 Sanusi Fafunwa Street, Victoria Island, Lagos',
    dropoff_address: 'Murtala Muhammed International Airport, Lagos',
    fare: null,
    distance_km: 22.4,
    started_at: '2024-05-12T14:10:00Z',
    completed_at: null,
    created_at: '2024-05-12T13:55:00Z',
  },
  {
    id: 'rid-002',
    rider_id: 'rdr-002',
    driver_id: 'drv-002',
    rider: { full_name: 'Oluwaseun Bakare' },
    driver: { full_name: 'Abiodun Salami' },
    trip_status: 'completed',
    service_tier: 'standard',
    pickup_address: '3 Awolowo Road, Ikoyi, Lagos',
    dropoff_address: '15 Adetokunbo Ademola Street, Victoria Island, Lagos',
    fare: 8500.00,
    distance_km: 6.1,
    started_at: '2024-05-12T11:00:00Z',
    completed_at: '2024-05-12T11:28:00Z',
    created_at: '2024-05-12T10:52:00Z',
  },
  {
    id: 'rid-003',
    rider_id: 'rdr-004',
    driver_id: 'drv-006',
    rider: { full_name: 'Adekunle Fashola' },
    driver: { full_name: 'Segun Adebayo' },
    trip_status: 'completed',
    service_tier: 'premium',
    pickup_address: 'Eko Hotel & Suites, Victoria Island, Lagos',
    dropoff_address: 'Lekki-Epe Expressway, Lekki Phase 1, Lagos',
    fare: 18000.00,
    distance_km: 14.7,
    started_at: '2024-05-12T09:30:00Z',
    completed_at: '2024-05-12T10:15:00Z',
    created_at: '2024-05-12T09:20:00Z',
  },
  {
    id: 'rid-004',
    rider_id: 'rdr-006',
    driver_id: 'drv-005',
    rider: { full_name: 'Taiwo Afolabi' },
    driver: { full_name: 'Chidi Nnamdi' },
    trip_status: 'cancelled',
    service_tier: 'standard',
    pickup_address: '10 Kingsway Road, Ikoyi, Lagos',
    dropoff_address: 'Lagos Island General Hospital',
    fare: null,
    distance_km: null,
    started_at: null,
    completed_at: null,
    created_at: '2024-05-12T08:40:00Z',
  },
  {
    id: 'rid-005',
    rider_id: 'rdr-001',
    driver_id: 'drv-002',
    rider: { full_name: 'Chioma Ibe' },
    driver: { full_name: 'Abiodun Salami' },
    trip_status: 'completed',
    service_tier: 'executive',
    pickup_address: '7 Bourdillon Road, Ikoyi, Lagos',
    dropoff_address: 'Four Points by Sheraton, Victoria Island, Lagos',
    fare: 11200.00,
    distance_km: 8.3,
    started_at: '2024-05-11T19:00:00Z',
    completed_at: '2024-05-11T19:34:00Z',
    created_at: '2024-05-11T18:52:00Z',
  },
];

export const MOCK_COMPLAINTS = [
  {
    id: 'cmp-001',
    trip_id: 'rid-002',
    complainant_type: 'rider',
    complainant_id: 'rdr-002',
    complainant: { full_name: 'Oluwaseun Bakare' },
    reported_user_id: 'drv-002',
    reported_user: { full_name: 'Abiodun Salami' },
    category: 'driver_complaint',
    severity: 'high',
    state: 'open',
    description: 'The driver was rude and refused to help with my luggage despite repeated requests. He also took a longer route than necessary which inflated the fare.',
    resolution_notes: null,
    assigned_to: 'adm-004',
    assigned_admin: { full_name: 'Tunde Adeyemi' },
    created_at: '2024-05-12T12:00:00Z',
    updated_at: '2024-05-12T12:00:00Z',
  },
  {
    id: 'cmp-002',
    trip_id: 'rid-003',
    complainant_type: 'rider',
    complainant_id: 'rdr-004',
    complainant: { full_name: 'Adekunle Fashola' },
    reported_user_id: null,
    reported_user: null,
    category: 'payment_issue',
    severity: 'medium',
    state: 'in_progress',
    description: 'I was charged ₦18,000 but my receipt shows ₦14,500. The difference of ₦3,500 was deducted from my wallet without explanation.',
    resolution_notes: null,
    assigned_to: 'adm-003',
    assigned_admin: { full_name: 'Fatimah Al-Hassan' },
    created_at: '2024-05-12T10:45:00Z',
    updated_at: '2024-05-12T11:30:00Z',
  },
  {
    id: 'cmp-003',
    trip_id: 'rid-001',
    complainant_type: 'driver',
    complainant_id: 'drv-001',
    complainant: { full_name: 'Emeka Obi' },
    reported_user_id: 'rdr-001',
    reported_user: { full_name: 'Chioma Ibe' },
    category: 'rider_complaint',
    severity: 'low',
    state: 'open',
    description: 'Rider asked me to make three unscheduled stops without updating the destination. Refused to pay additional fare for the extra distance.',
    resolution_notes: null,
    assigned_to: 'adm-004',
    assigned_admin: { full_name: 'Tunde Adeyemi' },
    created_at: '2024-05-12T14:55:00Z',
    updated_at: '2024-05-12T14:55:00Z',
  },
  {
    id: 'cmp-004',
    trip_id: 'rid-005',
    complainant_type: 'rider',
    complainant_id: 'rdr-001',
    complainant: { full_name: 'Chioma Ibe' },
    reported_user_id: 'drv-002',
    reported_user: { full_name: 'Abiodun Salami' },
    category: 'safety_report',
    severity: 'critical',
    state: 'escalated',
    description: 'Driver was driving erratically and appeared to be under the influence. I feared for my safety and asked to be let out before my destination. The vehicle smelled strongly of alcohol.',
    resolution_notes: null,
    assigned_to: 'adm-001',
    assigned_admin: { full_name: 'Adaeze Okafor' },
    created_at: '2024-05-11T20:10:00Z',
    updated_at: '2024-05-12T08:00:00Z',
  },
  {
    id: 'cmp-005',
    trip_id: 'rid-004',
    complainant_type: 'rider',
    complainant_id: 'rdr-006',
    complainant: { full_name: 'Taiwo Afolabi' },
    reported_user_id: null,
    reported_user: null,
    category: 'payment_issue',
    severity: 'low',
    state: 'resolved',
    description: 'My ride was cancelled by the driver but I was still charged a cancellation fee even though the driver cancelled, not me.',
    resolution_notes: 'Refund of ₦500 cancellation fee issued to rider wallet. Driver warned about incorrect cancellation logging.',
    assigned_to: 'adm-004',
    assigned_admin: { full_name: 'Tunde Adeyemi' },
    created_at: '2024-05-12T09:10:00Z',
    updated_at: '2024-05-12T13:00:00Z',
  },
];

export const MOCK_DASHBOARD_KPIS = {
  totalRevenue:           345050,
  totalRevenueTrend:      '+12.5%',
  activeDrivers:          45,
  activeDriversTrend:     '+3%',
  totalRiders:            1250,
  totalRidersTrend:       '+8.2%',
  pendingApplications:    12,
  pendingApplicationsTrend: '-1%',
};

export const MOCK_ACTIVITY_FEED = [
  {
    id: 'act-001',
    actor_role: 'ops_admin',
    actor: { full_name: 'Chukwuemeka Eze' },
    action: 'driver_approved',
    entity_type: 'drivers',
    entity_id: 'drv-001',
    metadata: { driver_name: 'Emeka Obi' },
    created_at: '2024-05-12T15:02:00Z',
  },
  {
    id: 'act-002',
    actor_role: 'support_agent',
    actor: { full_name: 'Tunde Adeyemi' },
    action: 'complaint_resolved',
    entity_type: 'complaints',
    entity_id: 'cmp-005',
    metadata: { rider_name: 'Taiwo Afolabi', resolution: 'Refund issued' },
    created_at: '2024-05-12T13:00:00Z',
  },
  {
    id: 'act-003',
    actor_role: 'ops_admin',
    actor: { full_name: 'Chukwuemeka Eze' },
    action: 'driver_suspended',
    entity_type: 'drivers',
    entity_id: 'drv-004',
    metadata: { driver_name: 'Kehinde Lawal', reason: 'Multiple safety complaints received' },
    created_at: '2024-05-12T11:45:00Z',
  },
  {
    id: 'act-004',
    actor_role: 'inspection_officer',
    actor: { full_name: 'Ngozi Nwosu' },
    action: 'inspection_completed',
    entity_type: 'inspections',
    entity_id: 'ins-003',
    metadata: { driver_name: 'Amina Suleiman', result: 'pass' },
    created_at: '2024-05-12T10:30:00Z',
  },
  {
    id: 'act-005',
    actor_role: 'finance_admin',
    actor: { full_name: 'Fatimah Al-Hassan' },
    action: 'commission_rate_updated',
    entity_type: 'global_settings',
    entity_id: null,
    metadata: { old_rate: '15%', new_rate: '13%' },
    created_at: '2024-05-12T09:00:00Z',
  },
  {
    id: 'act-006',
    actor_role: 'super_admin',
    actor: { full_name: 'Adaeze Okafor' },
    action: 'complaint_escalated',
    entity_type: 'complaints',
    entity_id: 'cmp-004',
    metadata: { complaint_category: 'safety_report', severity: 'critical' },
    created_at: '2024-05-12T08:00:00Z',
  },
];

export const MOCK_INSPECTIONS = [
  {
    id: 'ins-001',
    driver_id: 'drv-003',
    driver: { full_name: 'Ifeanyi Okeke', phone: '+234 803 456 7890' },
    vehicle_id: 'veh-003',
    vehicle: { make: 'Toyota', model: 'Sienna', plate_number: 'LND 201 XY' },
    application_id: 'app-001',
    scheduled_at: '2024-05-14T10:00:00Z',
    location: 'Chauffeur Operations Hub, 5 Idejo Street, Victoria Island, Lagos',
    assigned_inspector_id: 'adm-005',
    assigned_inspector: { full_name: 'Ngozi Nwosu' },
    notes_for_driver: 'Please bring original copies of all documents and arrive 10 minutes early.',
    vehicle_condition: null,
    document_verification: null,
    identity_match: null,
    inspector_notes: null,
    result: 'pending',
    completed_at: null,
    created_at: '2024-05-11T09:00:00Z',
  },
  {
    id: 'ins-002',
    driver_id: 'drv-008',
    driver: { full_name: 'Amina Suleiman', phone: '+234 808 901 2345' },
    vehicle_id: 'veh-006',
    vehicle: { make: 'Hyundai', model: 'Sonata', plate_number: 'LND 776 QR' },
    application_id: 'app-003',
    scheduled_at: '2024-05-13T14:00:00Z',
    location: 'Chauffeur Operations Hub, 5 Idejo Street, Victoria Island, Lagos',
    assigned_inspector_id: 'adm-005',
    assigned_inspector: { full_name: 'Ngozi Nwosu' },
    notes_for_driver: 'Vehicle must be clean and all documents must be originals.',
    vehicle_condition: 'pass',
    document_verification: 'pass',
    identity_match: 'pass',
    inspector_notes: 'All clear. Vehicle is in excellent condition. Documents verified. Driver identity matches submission.',
    result: 'pass',
    completed_at: '2024-05-13T14:45:00Z',
    created_at: '2024-05-09T14:20:00Z',
  },
  {
    id: 'ins-003',
    driver_id: 'drv-009',
    driver: { full_name: 'Olu Martins', phone: '+234 809 012 3456' },
    vehicle_id: 'veh-007',
    vehicle: { make: 'Kia', model: 'Optima', plate_number: 'LND 445 ST' },
    application_id: 'app-005',
    scheduled_at: '2024-05-07T11:00:00Z',
    location: 'Chauffeur Operations Hub, 5 Idejo Street, Victoria Island, Lagos',
    assigned_inspector_id: 'adm-005',
    assigned_inspector: { full_name: 'Ngozi Nwosu' },
    notes_for_driver: null,
    vehicle_condition: 'fail',
    document_verification: 'pass',
    identity_match: 'pass',
    inspector_notes: 'Vehicle has visible body damage on the rear bumper and right rear door. Interior has strong cigarette odour. Not suitable for premium ride-hailing. Documents and identity are fine.',
    result: 'fail',
    completed_at: '2024-05-07T11:50:00Z',
    created_at: '2024-05-06T13:00:00Z',
  },
];

export const MOCK_VIP_BOOKINGS = [
  {
    id: 'vip-001',
    rider_id: 'rdr-004',
    rider: { full_name: 'Adekunle Fashola', phone: '+234 814 567 8901', email: 'adekunle.f@hotmail.com' },
    driver_id: 'drv-001',
    driver: { full_name: 'Emeka Obi', phone: '+234 801 234 5678', rating: 4.9 },
    vehicle_id: 'vveh-001',
    vehicle: { make: 'Mercedes-Benz', model: 'S-Class', plate_number: 'VIP 001 LG', colour: 'Obsidian Black' },
    booking_type: 'scheduled',
    status: 'confirmed',
    pickup_address: 'Federal Palace Hotel, Victoria Island, Lagos',
    pickup_lat: 6.4281,
    pickup_lng: 3.4219,
    destination_address: 'Nnamdi Azikiwe International Airport, Abuja',
    destination_lat: 9.0068,
    destination_lng: 7.2632,
    scheduled_at: '2024-05-15T06:00:00Z',
    started_at: null,
    completed_at: null,
    fare: 250000.00,
    special_requests: 'Client is a government official. Discretion required. Please have chilled water and newspaper in vehicle.',
    admin_notes: 'Priority booking — escalate any issues immediately to super admin.',
    assigned_by: 'adm-002',
    created_at: '2024-05-10T14:00:00Z',
    updated_at: '2024-05-10T16:30:00Z',
  },
  {
    id: 'vip-002',
    rider_id: 'rdr-001',
    rider: { full_name: 'Chioma Ibe', phone: '+234 811 234 5678', email: 'chioma.ibe@gmail.com' },
    driver_id: null,
    vehicle_id: null,
    booking_type: 'instant',
    status: 'pending',
    pickup_address: 'Eko Hotel & Suites, Victoria Island, Lagos',
    pickup_lat: 6.4355,
    pickup_lng: 3.4197,
    destination_address: 'Landmark Beach Resort, Oniru, Lagos',
    destination_lat: 6.4490,
    destination_lng: 3.4620,
    scheduled_at: null,
    started_at: null,
    completed_at: null,
    fare: null,
    special_requests: 'Travelling with two large suitcases. Needs SUV or large saloon.',
    admin_notes: null,
    assigned_by: null,
    created_at: '2024-05-12T15:30:00Z',
    updated_at: '2024-05-12T15:30:00Z',
  },
  {
    id: 'vip-003',
    rider_id: 'rdr-002',
    rider: { full_name: 'Oluwaseun Bakare', phone: '+234 812 345 6789', email: 'seun.bakare@yahoo.com' },
    driver_id: 'drv-006',
    driver: { full_name: 'Segun Adebayo', phone: '+234 806 789 0123', rating: 4.8 },
    vehicle_id: 'vveh-002',
    vehicle: { make: 'BMW', model: '7 Series', plate_number: 'VIP 002 LG', colour: 'Arctic Silver' },
    booking_type: 'scheduled',
    status: 'in_progress',
    pickup_address: 'Transcorp Hilton, Maitama, Abuja',
    pickup_lat: 9.0720,
    pickup_lng: 7.4943,
    destination_address: 'Aso Rock Presidential Villa, Abuja',
    destination_lat: 9.0527,
    destination_lng: 7.5126,
    scheduled_at: '2024-05-12T14:00:00Z',
    started_at: '2024-05-12T14:05:00Z',
    completed_at: null,
    fare: 85000.00,
    special_requests: null,
    admin_notes: 'Corporate account — invoice required.',
    assigned_by: 'adm-001',
    created_at: '2024-05-09T09:00:00Z',
    updated_at: '2024-05-12T14:05:00Z',
  },
  {
    id: 'vip-004',
    rider_id: 'rdr-006',
    rider: { full_name: 'Taiwo Afolabi', phone: '+234 816 789 0123', email: 'taiwo.a@gmail.com' },
    driver_id: 'drv-002',
    driver: { full_name: 'Abiodun Salami', phone: '+234 802 345 6789', rating: 4.7 },
    vehicle_id: 'vveh-001',
    vehicle: { make: 'Mercedes-Benz', model: 'S-Class', plate_number: 'VIP 001 LG', colour: 'Obsidian Black' },
    booking_type: 'instant',
    status: 'completed',
    pickup_address: 'Murtala Muhammed Airport Terminal 2, Lagos',
    pickup_lat: 6.5774,
    pickup_lng: 3.3215,
    destination_address: '1 Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
    destination_lat: 6.4295,
    destination_lng: 3.4176,
    scheduled_at: null,
    started_at: '2024-05-11T16:10:00Z',
    completed_at: '2024-05-11T17:05:00Z',
    fare: 45000.00,
    special_requests: 'Airport pickup — flight EK804 from Dubai. Flight lands at 15:45.',
    admin_notes: null,
    assigned_by: 'adm-002',
    created_at: '2024-05-11T12:00:00Z',
    updated_at: '2024-05-11T17:05:00Z',
  },
];

export const MOCK_VIP_VEHICLES = [
  {
    id: 'vveh-001',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2024,
    plate_number: 'VIP 001 LG',
    colour: 'Obsidian Black',
    status: 'in_use',
    exterior_image_urls: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    ],
    interior_image_urls: [
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=400',
    ],
    amenities: ['Wi-Fi', 'Leather Seats', 'Chilled Water', 'Privacy Screen', 'Phone Charger'],
    capacity: 4,
    description: 'Our flagship executive sedan — the pinnacle of chauffeur-driven luxury.',
    added_by: 'adm-001',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'vveh-002',
    make: 'BMW',
    model: '7 Series',
    year: 2023,
    plate_number: 'VIP 002 LG',
    colour: 'Arctic Silver',
    status: 'available',
    exterior_image_urls: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    ],
    interior_image_urls: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=400',
    ],
    amenities: ['Wi-Fi', 'Leather Seats', 'Chilled Water', 'Sunroof', 'Phone Charger'],
    capacity: 4,
    description: 'Premium German engineering with supreme comfort for discerning passengers.',
    added_by: 'adm-001',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'vveh-003',
    make: 'Range Rover',
    model: 'Autobiography',
    year: 2024,
    plate_number: 'VIP 003 LG',
    colour: 'Carpathian Grey',
    status: 'available',
    exterior_image_urls: [
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=400',
    ],
    interior_image_urls: [
      'https://images.unsplash.com/photo-1441148345475-03a2e82f9719?w=400',
    ],
    amenities: ['Wi-Fi', 'Leather Seats', 'Chilled Water', 'Privacy Screen', 'Child Seat Available', 'Tinted Windows'],
    capacity: 6,
    description: 'The ultimate luxury SUV — commanding presence with unmatched interior space.',
    added_by: 'adm-002',
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    id: 'vveh-004',
    make: 'Toyota',
    model: 'Alphard',
    year: 2023,
    plate_number: 'VIP 004 LG',
    colour: 'Pearl White',
    status: 'maintenance',
    exterior_image_urls: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    ],
    interior_image_urls: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    ],
    amenities: ['Wi-Fi', 'Leather Seats', 'Chilled Water', 'TV Screen', 'Phone Charger', 'Tissue Box'],
    capacity: 7,
    description: 'Spacious executive MPV — ideal for families and group travel.',
    added_by: 'adm-002',
    created_at: '2024-03-01T00:00:00Z',
  },
];

export const MOCK_SOS_ALERTS = [
  {
    id: 'sos-001',
    triggered_by: 'rider',
    user_id: 'rdr-003',
    user: { full_name: 'Maryam Aliyu', phone: '+234 813 456 7890', selfie_url: 'https://i.pravatar.cc/150?img=23' },
    ride_id: 'rid-006',
    ride: { pickup_address: '12 Bode Thomas Street, Surulere, Lagos', dropoff_address: 'Lagos Mainland Hospital' },
    sos_type: 'voice_recording',
    message_text: null,
    voice_recording_url: '/mock/audio/sos_001.mp3',
    voice_duration_seconds: 47,
    status: 'active',
    location_address: '34 Bode Thomas Street, Surulere, Lagos',
    location_lat: 6.5010,
    location_lng: 3.3560,
    triggered_at: '2024-05-12T15:41:00Z',
    first_responded_by: null,
    first_responded_at: null,
    resolved_by: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: '2024-05-12T15:41:00Z',
  },
  {
    id: 'sos-002',
    triggered_by: 'driver',
    user_id: 'drv-005',
    user: { full_name: 'Chidi Nnamdi', phone: '+234 805 678 9012', selfie_url: 'https://i.pravatar.cc/150?img=15' },
    ride_id: 'rid-007',
    ride: { pickup_address: 'Oshodi Bus Terminal, Lagos', dropoff_address: 'Mile 2, Amuwo Odofin, Lagos' },
    sos_type: 'message',
    message_text: 'Passenger is threatening me with a weapon. I am currently stopped on the bridge. Please send help immediately. Plate number LND 119 ZZ.',
    voice_recording_url: null,
    voice_duration_seconds: null,
    status: 'responding',
    location_address: 'Third Mainland Bridge, Lagos (Near Adeniji interchange)',
    location_lat: 6.5120,
    location_lng: 3.3790,
    triggered_at: '2024-05-12T14:23:00Z',
    first_responded_by: 'adm-002',
    first_responded_at: '2024-05-12T14:24:00Z',
    resolved_by: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: '2024-05-12T14:23:00Z',
  },
  {
    id: 'sos-003',
    triggered_by: 'rider',
    user_id: 'rdr-005',
    user: { full_name: 'Zainab Umar', phone: '+234 815 678 9012', selfie_url: 'https://i.pravatar.cc/150?img=25' },
    ride_id: null,
    ride: null,
    sos_type: 'message',
    message_text: 'I booked a ride and the driver is not following the app route. He has taken me to an unfamiliar area. I am scared.',
    voice_recording_url: null,
    voice_duration_seconds: null,
    status: 'resolved',
    location_address: 'Ikorodu Road, Ketu, Lagos',
    location_lat: 6.5940,
    location_lng: 3.3820,
    triggered_at: '2024-05-11T21:05:00Z',
    first_responded_by: 'adm-004',
    first_responded_at: '2024-05-11T21:06:00Z',
    resolved_by: 'adm-002',
    resolved_at: '2024-05-11T21:55:00Z',
    resolution_notes: 'Driver contacted and warned. Rider safely reached destination via alternate driver. Driver account flagged for review. Police report advised.',
    created_at: '2024-05-11T21:05:00Z',
  },
];

export const MOCK_SOS_ACTIONS = [
  {
    id: 'sact-001',
    sos_id: 'sos-002',
    admin_id: 'adm-002',
    admin: { full_name: 'Chukwuemeka Eze', role: 'ops_admin' },
    action_type: 'opened',
    action_notes: null,
    created_at: '2024-05-12T14:24:00Z',
  },
  {
    id: 'sact-002',
    sos_id: 'sos-002',
    admin_id: 'adm-002',
    admin: { full_name: 'Chukwuemeka Eze', role: 'ops_admin' },
    action_type: 'called_user',
    action_notes: 'Called driver on +234 805 678 9012. Line connected. Driver confirmed he is on Third Mainland Bridge near Adeniji. Passenger still in vehicle.',
    created_at: '2024-05-12T14:25:00Z',
  },
  {
    id: 'sact-003',
    sos_id: 'sos-002',
    admin_id: 'adm-002',
    admin: { full_name: 'Chukwuemeka Eze', role: 'ops_admin' },
    action_type: 'called_emergency',
    action_notes: 'Called Lagos State Emergency Management Agency (LASEMA) on 767. Provided vehicle plate number LND 119 ZZ and location.',
    created_at: '2024-05-12T14:27:00Z',
  },
  {
    id: 'sact-004',
    sos_id: 'sos-002',
    admin_id: 'adm-001',
    admin: { full_name: 'Adaeze Okafor', role: 'super_admin' },
    action_type: 'escalated',
    action_notes: 'Escalated to super admin. Monitoring situation. Emergency services en route.',
    created_at: '2024-05-12T14:28:00Z',
  },
  {
    id: 'sact-005',
    sos_id: 'sos-003',
    admin_id: 'adm-004',
    admin: { full_name: 'Tunde Adeyemi', role: 'support_agent' },
    action_type: 'opened',
    action_notes: null,
    created_at: '2024-05-11T21:06:00Z',
  },
  {
    id: 'sact-006',
    sos_id: 'sos-003',
    admin_id: 'adm-004',
    admin: { full_name: 'Tunde Adeyemi', role: 'support_agent' },
    action_type: 'called_user',
    action_notes: 'Called rider. She is okay but shaken. Staying on the line.',
    created_at: '2024-05-11T21:08:00Z',
  },
  {
    id: 'sact-007',
    sos_id: 'sos-003',
    admin_id: 'adm-002',
    admin: { full_name: 'Chukwuemeka Eze', role: 'ops_admin' },
    action_type: 'resolved',
    action_notes: 'Driver contacted and warned. Rider safely reached destination via alternate driver. Driver account flagged for review. Police report advised.',
    created_at: '2024-05-11T21:55:00Z',
  },
];

export const MOCK_CONTENT_ITEMS = [
  {
    id: 'cnt-001',
    content_type: 'faq',
    audience: 'rider',
    title: 'Rider Frequently Asked Questions',
    body: '<h2>How do I book a ride?</h2><p>Open the Chauffeur app, enter your pickup and destination, select your service tier, and tap Book Now.</p><h2>What payment methods are accepted?</h2><p>We accept wallet credits, debit cards, bank transfers, and cash. You can top up your wallet from the app.</p><h2>Can I schedule a ride in advance?</h2><p>Yes — tap "Schedule Ride" when booking and select your preferred date and time up to 7 days in advance.</p><h2>What if I need to cancel?</h2><p>You can cancel for free up to 3 minutes after booking. After that, a cancellation fee may apply.</p>',
    status: 'published',
    version: 3,
    published_at: '2024-05-10T09:00:00Z',
    published_by: 'adm-001',
    publisher: { full_name: 'Adaeze Okafor' },
    created_by: 'adm-002',
    updated_by: 'adm-001',
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-05-10T09:00:00Z',
  },
  {
    id: 'cnt-002',
    content_type: 'privacy_policy',
    audience: 'both',
    title: 'Privacy Policy',
    body: '<h1>Chauffeur Privacy Policy</h1><p>Last updated: 10 May 2024</p><p>Chauffeur Technologies Ltd ("we", "our", or "us") is committed to protecting your personal information. This Privacy Policy explains how we collect, use, store, and share information when you use our platform.</p><h2>Information We Collect</h2><p>We collect information you provide directly to us, such as your name, email address, phone number, and payment information when you register for an account.</p>',
    status: 'published',
    version: 2,
    published_at: '2024-04-01T12:00:00Z',
    published_by: 'adm-001',
    publisher: { full_name: 'Adaeze Okafor' },
    created_by: 'adm-001',
    updated_by: 'adm-001',
    created_at: '2024-01-15T09:00:00Z',
    updated_at: '2024-04-01T12:00:00Z',
  },
  {
    id: 'cnt-003',
    content_type: 'terms_of_service',
    audience: 'driver',
    title: 'Driver Terms of Service',
    body: '<h1>Driver Terms of Service</h1><p>By registering as a Chauffeur driver, you agree to the following terms and conditions. Please read them carefully before proceeding with your application.</p><h2>Eligibility</h2><p>You must be at least 21 years of age, hold a valid Nigerian driver\'s licence, and own or have authorised access to a vehicle that meets our quality standards.</p>',
    status: 'published',
    version: 1,
    published_at: '2024-02-01T10:00:00Z',
    published_by: 'adm-001',
    publisher: { full_name: 'Adaeze Okafor' },
    created_by: 'adm-001',
    updated_by: 'adm-001',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'cnt-004',
    content_type: 'company_policy',
    audience: 'driver',
    title: 'Driver Code of Conduct',
    body: '<h1>Driver Code of Conduct</h1><p>As a Chauffeur driver, you represent our brand and our commitment to excellence. The following policies must be adhered to at all times while operating on the Chauffeur platform.</p><h2>Professional Appearance</h2><p>Drivers must wear a clean, pressed white or black collared shirt and dark trousers at all times while on duty.</p>',
    status: 'draft',
    version: 1,
    published_at: null,
    published_by: null,
    publisher: null,
    created_by: 'adm-002',
    updated_by: 'adm-002',
    created_at: '2024-05-08T14:00:00Z',
    updated_at: '2024-05-11T16:30:00Z',
  },
];

export const MOCK_EARNINGS_OVERVIEW = {
  totalDriverEarnings: 8742000,   // ₦87,420.00
  totalPlatformCommission: 1548000, // ₦15,480.00
  pendingPayouts: 3210000,        // ₦32,100.00
  successfulWithdrawals: 5532000, // ₦55,320.00
};

export const MOCK_DRIVER_EARNINGS = [
  {
    driver_id: 'drv-001',
    driver: { full_name: 'Emeka Obi', rating: 4.9 },
    completed_rides: 142,
    gross_earnings: 1420000,
    commission_deducted: 213000,
    net_payout: 1207000,
    commission_rate: 15,
  },
  {
    driver_id: 'drv-002',
    driver: { full_name: 'Abiodun Salami', rating: 4.7 },
    completed_rides: 118,
    gross_earnings: 1062000,
    commission_deducted: 127440,
    net_payout: 934560,
    commission_rate: 12,
  },
  {
    driver_id: 'drv-005',
    driver: { full_name: 'Chidi Nnamdi', rating: 4.6 },
    completed_rides: 97,
    gross_earnings: 776000,
    commission_deducted: 116400,
    net_payout: 659600,
    commission_rate: 15,
  },
  {
    driver_id: 'drv-006',
    driver: { full_name: 'Segun Adebayo', rating: 4.8 },
    completed_rides: 203,
    gross_earnings: 2030000,
    commission_deducted: 203000,
    net_payout: 1827000,
    commission_rate: 10,
  },
];

export const MOCK_WALLET_TRANSACTIONS = [
  {
    id: 'txn-001',
    rider_id: 'rdr-001',
    rider: { full_name: 'Chioma Ibe' },
    type: 'top_up',
    amount: 50000,
    reason: null,
    created_at: '2024-05-10T09:30:00Z',
  },
  {
    id: 'txn-002',
    rider_id: 'rdr-001',
    rider: { full_name: 'Chioma Ibe' },
    type: 'ride_payment',
    amount: -11200,
    reason: null,
    created_at: '2024-05-11T19:34:00Z',
  },
  {
    id: 'txn-003',
    rider_id: 'rdr-006',
    rider: { full_name: 'Taiwo Afolabi' },
    type: 'refund',
    amount: 500,
    reason: 'Driver-initiated cancellation — cancellation fee reversed',
    created_at: '2024-05-12T13:00:00Z',
  },
  {
    id: 'txn-004',
    rider_id: 'rdr-004',
    rider: { full_name: 'Adekunle Fashola' },
    type: 'manual_adjustment',
    amount: -3500,
    reason: 'Disputed fare difference — under investigation. Deducted pending resolution.',
    created_at: '2024-05-12T11:00:00Z',
  },
];

export const MOCK_RIDE_ANALYTICS = {
  accepted: 3,
  onTheWay: 1,
  arrived: 2,
  pickup: 1,
  starting: 1,
  completed: 11,
  cancelled: 31,
};

export const MOCK_USER_OVERVIEW = {
  totalUsers: 33,
  riders: 23,
  drivers: 10,
  realtimeNow: 4,
  trend: '+12%',
  chartData: {
    riders:  { labels: ['06-12pm', '12-06pm', '06-12am', '12-06am'], data: [12, 18, 6, 4] },
    drivers: { labels: ['06-12pm', '12-06pm', '06-12am', '12-06am'], data: [5, 8, 3, 2]  },
  },
};

export const MOCK_ADMIN_WALLET = {
  totalEarning: 1087200,
  trend: '+79.2%',
  alreadyWithdrawn: 0,
  pendingWithdraw: 4800000,
  totalCommission: 1548000,
  rejectedWithdraw: 0,
};

export const MOCK_TOP_DRIVERS = [
  { rank: 1, driver_id: 'drv-001', name: 'Emeka Obi', avatar: 'https://i.pravatar.cc/150?img=11', rating: 4.9, rides: 142 },
  { rank: 2, driver_id: 'drv-006', name: 'Segun Adebayo', avatar: 'https://i.pravatar.cc/150?img=16', rating: 4.8, rides: 118 },
  { rank: 3, driver_id: 'drv-002', name: 'Abiodun Salami', avatar: 'https://i.pravatar.cc/150?img=12', rating: 4.7, rides: 97 },
  { rank: 4, driver_id: 'drv-005', name: 'Chidi Nnamdi', avatar: 'https://i.pravatar.cc/150?img=15', rating: 4.6, rides: 83 },
  { rank: 5, driver_id: 'drv-004', name: 'Kehinde Lawal', avatar: 'https://i.pravatar.cc/150?img=14', rating: 4.2, rides: 61 },
];
